name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: apt update
      - run: apt install build-essential bc bison flex libncurses5-dev libssl-dev gcc-aarch64-linux-gnu lz4
      - run: git clone https://github.com/kerneltoast/android_kernel_google_zuma.git
      - run: cd ./android_kernel_google_zuma
      - run: make zuma_defconf
      - run: make -j$(nproc)
      - run: cd ./out/google-modules/soc/gs/arch/arm64/boot/dts/google
      - run: cat *.dtb > dtb
      - run: cp ./dtb ../../../../../..
      - run: cd ~/android_kernel_google_zuma
      - run: cd ../../../../../../..
      - run: 
      - run: 
      - run: 
