name: GitHub Actions Kernel Build
run-name: ${{ github.actor }} is building the kernel 🚀

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Update and Upgrade Dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y build-essential bc bison flex libncurses5-dev libssl-dev gcc-aarch64-linux-gnu lz4 zip libelf-dev liblz4-tool liblzma-dev

      - name: Clone Repositories
        run: |
          git clone https://github.com/kerneltoast/android_kernel_google_zuma.git
          git clone https://github.com/TheWildJames/SultanSU.git

      - name: Setup KernelSU
        run: |
          cd android_kernel_google_zuma
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Compile the Kernel
        run: |
          cd android_kernel_google_zuma
          make zuma_defconfig
          make -j$(nproc)
